<?php
/** @var Ecocode_Profiler_Block_Collector_Base $this */

/** @var Ecocode_Profiler_Model_Collector_RequestDataCollector $collector */
$collector = $this->getCollector();

/** @var Ecocode_Profiler_Helper_Renderer $renderHelper */
$renderHelper = Mage::helper('ecocode_profiler/renderer');
?>


<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title">Request</h3>

        <div class="tab-content">
            <h3>GET Parameters</h3>

            <?php if (!count($collector->getRequestQuery())): ?>
                <div class="empty">
                    <p>No GET parameters</p>
                </div>
            <?php else: ?>
                <?php echo $renderHelper->renderBag($collector->getRequestQuery()) ?>
            <?php endif ?>

            <h3>POST Parameters</h3>

            <?php if (!count($collector->getRequestRequest())): ?>
                <div class="empty">
                    <p>No POST parameters</p>
                </div>
            <?php else: ?>
                <?php echo $renderHelper->renderBag($collector->getRequestRequest()) ?>
            <?php endif ?>

            <h3>Request Attributes</h3>

            <?php if (!count($collector->getRequestAttributes())): ?>
                <div class="empty">
                    <p>No attributes</p>
                </div>
            <?php else: ?>
                <?php echo $renderHelper->renderBag($collector->getRequestAttributes()) ?>
            <?php endif ?>

            <h3>Cookies</h3>

            <?php if (!count($collector->getRequestCookies())): ?>
                <div class="empty">
                    <p>No cookies</p>
                </div>
            <?php else: ?>
                <?php echo $renderHelper->renderBag($collector->getRequestCookies()) ?>
            <?php endif ?>

            <h3>Request Headers</h3>
            <?php echo $renderHelper->renderBag($collector->getRequestHeaders()) ?>

            <h3>Request Content</h3>

            <?php if ($collector->getContent() === false): ?>
                <div class="empty">
                    <p>Request content not available (it was retrieved as a resource).</p>
                </div>
            <?php elseif ($collector->getContent()): ?>
                <div class="card">
                    <pre class="break-long-words"><?php echo $collector->getContent() ?></pre>
                </div>
            <?php else: ?>
                <div class="empty">
                    <p>No content</p>
                </div>
            <?php endif ?>

            <h3>Server Parameters</h3>
            <?php echo $renderHelper->renderBag($collector->getRequestServer()) ?>
        </div>
    </div>

    <div class="tab">
        <h3 class="tab-title">Response</h3>

        <div class="tab-content">
            <h3>Response Headers</h3>

            <?php echo $renderHelper->renderBag($collector->getResponseHeaders()) ?>
        </div>
    </div>

    <?php $sessionMetadata = $collector->getSessionMetadata() ?>
    <?php $sessionAttributes = $collector->getSessionAttributes() ?>

    <div class="tab <?php echo !($sessionMetadata && $sessionAttributes) ? '' : 'disabled' ?>">
        <h3 class="tab-title">Session</h3>

        <div class="tab-content">
            <h3>Session Metadata</h3>

            <?php if (empty($sessionMetadata)): ?>
                <div class="empty">
                    <p>No session metadata</p>
                </div>
            <?php else: ?>
                <?php echo $renderHelper->renderTable($sessionMetadata); ?>
            <?php endif ?>

            <h3>Sessions</h3>

            <?php if (empty($sessionAttributes)): ?>
                <div class="empty">
                    <p>No session attributes</p>
                </div>
            <?php else: ?>
                <?php foreach ($sessionAttributes['namespace'] as $namespace => $data): ?>
                    <h4><?php echo uc_words($namespace) ?></h4>
                    <?php echo $renderHelper->renderTable($data); ?>
                <?php endforeach; ?>


                <?php foreach ($sessionAttributes['store'] as $namespace => $data): ?>
                    <h4><?php echo uc_words($namespace) ?></h4>
                    <?php echo $renderHelper->renderTable($data); ?>
                <?php endforeach; ?>

                <?php foreach ($sessionAttributes['global'] as $namespace => $data): ?>
                    <h4><?php echo uc_words($namespace) ?></h4>
                    <?php echo $renderHelper->renderTable($data); ?>
                <?php endforeach; ?>
            <?php endif ?>

        </div>
    </div>

    <div class="tab <?php echo $collector->getMessages() ? '' : 'disabled' ?>">
        <h3 class="tab-title">Messages <span class="badge"><?php echo count($collector->getMessages()) ?></span></h3>

        <div class="tab-content">
            <h3>Messages</h3>

            <?php if (empty($collector->getMessages())): ?>
                <div class="empty">
                    <p>No messages were created.</p>
                </div>
            <?php else: ?>
                <table>
                    <thead>
                    <tr>
                        <th scope="col">Session</th>
                        <th scope="col">Namespace</th>
                        <th scope="col">Type</th>
                        <th class="nowrap">Message</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($collector->getMessages() as $message): ?>
                        <tr>
                            <td class="nowrap" scope="row"><?php echo $message['class_group'] ?></td>
                            <td class="nowrap"><?php echo $message['namespace'] ?></td>
                            <td class="nowrap"><?php echo $message['type'] ?></td>
                            <td><?php echo $message['text'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            <?php endif; ?>
        </div>
    </div>
    <!--
        {% if profile.parent %}
        <div class="tab">
            <h3 class="tab-title">Parent Request</h3>

            <div class="tab-content">
                <h3>
                    <a href="{{ path('_profiler', { token: profile.parent.token }) }}">Return to parent request</a>
                    <small>(token = {{ profile.parent.token }})</small>
                </h3>

                {{ include('@WebProfiler/Profiler/bag.html.twig', { bag: profile.parent.getcollector('request').requestattributes }, with_context = false) }}
            </div>
        </div>
        {% endif %}

        {% if profile.children|length %}
        <div class="tab">
            <h3 class="tab-title">Sub Requests <span class="badge">{{ profile.children|length }}</span></h3>

            <div class="tab-content">
                {% for child in profile.children %}
                <h3>
                    <a href="{{ path('_profiler', { token: child.token }) }}">
                        {{- child.getcollector('request').requestattributes.get('_controller') -}}
                    </a>
                    <small>(token = {{ child.token }})</small>
                </h3>

                {{ include('@WebProfiler/Profiler/bag.html.twig', { bag: child.getcollector('request').requestattributes }, with_context = false) }}
                {% endfor %}
            </div>
        </div>
        {% endif %}-->
</div>
