<?php
/** @var Ecocode_Profiler_Block_Collector_Base $this */

/** @var Ecocode_Profiler_Model_Collector_ConfigDataCollector $collector */
$collector = $this->getCollector();
$iconYes   = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="28" height="28" viewBox="0 0 12 12" enable-background="new 0 0 12 12" xml:space="preserve">
    <path fill="#5E976E" d="M12,3.1c0,0.4-0.1,0.8-0.4,1.1L5.9,9.8c-0.3,0.3-0.6,0.4-1,0.4c-0.4,0-0.7-0.1-1-0.4L0.4,6.3
    C0.1,6,0,5.6,0,5.2c0-0.4,0.2-0.7,0.4-0.9C0.6,4,1,3.9,1.3,3.9c0.4,0,0.8,0.1,1.1,0.4l2.5,2.5l4.7-4.7c0.3-0.3,0.7-0.4,1-0.4
    c0.4,0,0.7,0.2,0.9,0.4C11.8,2.4,12,2.7,12,3.1z"/>
</svg>';
$iconNo    = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="28" height="28" viewBox="0 0 12 12" enable-background="new 0 0 12 12" xml:space="preserve">
    <path fill="#B0413E" d="M10.4,8.4L8,6l2.4-2.4c0.8-0.8,0.7-1.6,0.2-2.2C10,0.9,9.2,0.8,8.4,1.6L6,4L3.6,1.6C2.8,0.8,2,0.9,1.4,1.4
    C0.9,2,0.8,2.8,1.6,3.6L4,6L1.6,8.4C0.8,9.2,0.9,10,1.4,10.6c0.6,0.6,1.4,0.6,2.2-0.2L6,8l2.4,2.4c0.8,0.8,1.6,0.7,2.2,0.2
    C11.1,10,11.2,9.2,10.4,8.4z"/>
</svg>';

?>
<h2>PHP Configuration</h2>

<div class="metrics">
    <div class="metric">
        <span class="value"><?php echo $collector->getPhpVersion() ?></span>
        <span class="label">PHP version</span>
    </div>

    <div class="metric">
        <span class="value"><?php echo $collector->hasAccelerator() ? $iconYes : $iconNo; ?></span>
        <span class="label">PHP acceleration</span>
    </div>

    <div class="metric">
        <span class="value"><?php echo $collector->hasXDebug() ? $iconYes : $iconNo; ?></span>
        <span class="label">Xdebug</span>
    </div>
</div>

<div class="metrics metrics-horizontal">
    <div class="metric">
        <span
        <span class="value"><?php echo $collector->hasZendOpcache() ? $iconYes : $iconNo; ?></span>
        <span class="label">OPcache</span>
    </div>

    <div class="metric">
        <span class="value"><?php echo $collector->hasApc() ? $iconYes : $iconNo; ?></span>
        <span class="label">APC</span>
    </div>

    <div class="metric">
        <span class="value"><?php echo $collector->hasXCache() ? $iconYes : $iconNo; ?></span>
        <span class="label">XCache</span>
    </div>

    <div class="metric">
        <span
        <span class="value"><?php echo $collector->hasEAccelerator() ? $iconYes : $iconNo; ?></span>
        <span class="label">EAccelerator</span>
    </div>
</div>

<p>
    <a href="<?php echo Mage::getUrl('_profiler/index/phpinfo') ?>">View full PHP configuration</a>
</p>


<h2>Magento</h2>
<table>
    <thead>
    <tr>
        <th class="key">Key</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Admin Url</td>
        <td><?php $adminUrl = Mage::helper('adminhtml')->getUrl('adminhtml'); ?>
            <a href="<?php echo $adminUrl ?>"><?php echo $adminUrl ?></a>
        </td>
    </tr>
    <tr>
        <td>Website</td>
        <td><?php echo $collector->getWebsiteName() ?> (<?php echo $collector->getWebsiteCode() ?>)</td>
    </tr>
    <tr>
        <td>Store</td>
        <td><?php echo $collector->getStoreName() ?> (<?php echo $collector->getStoreCode() ?>)</td>
    </tr>
    </tbody>
</table>


<h2>Modules</h2>
<?php $activeModules = $collector->geModulesByState(true); ?>
<?php $inActiveModules = $collector->geModulesByState(false); ?>
<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title">Enabled Modules
            <small>(<?php echo count($activeModules) ?>)</small>
        </h3>


        <div class="tab-content">
            <table>
                <thead>
                <tr>
                    <th>Module</th>
                    <th>Namespace</th>
                    <th>Version</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($activeModules as $name => $data): ?>
                    <tr>
                        <td><?php echo $name ?></td>
                        <td><?php echo $data['codePool'] ?></td>
                        <td><?php echo isset($data['version']) ? $data['version'] : '?' ?></td>
                    </tr>

                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="tab">
        <h3 class="tab-title">Disables Modules
            <small>(<?php echo count($inActiveModules) ?>)</small>
        </h3>


        <div class="tab-content">
            <table>
                <thead>
                <tr>
                    <th>Module</th>
                    <th>Namespace</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($inActiveModules as $name => $data): ?>
                    <tr>
                        <td><?php echo $name ?></td>
                        <td><?php echo isset($data['codePool']) ? $data['codePool'] : '?' ?></td>
                    </tr>

                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
