<?php
/** @var Ecocode_Profiler_Model_Collector_ConfigDataCollector $collector */
$collector = $this->getCollector();
$token     = $this->getToken();
?>


<div
    class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getName() ?> sf-toolbar-status-normal sf-toolbar-block-right">
    <div class="sf-toolbar-icon">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="svgMageLogo" width="24" xml:space="preserve" height="24" viewBox="0 0 53.692 62" baseProfile="" version="1.1" y="0px" x="0px">
            <g fill="#AAA">
                <path d="m26.845 8.857"/><polygon points="53.692 15.5 53.692 46.5 46.021 50.929 46.021 19.929 26.845 8.857 7.67 19.928 7.67 50.929 0 46.5 0 15.5 26.845 0"/><polygon points="26.847 62 15.341 55.356 15.341 24.357 23.011 19.928 23.011 50.929 26.845 53.257 30.682 50.929 30.682 19.929 38.353 24.357 38.353 55.356"/>
            </g>
        </svg>
        <span class="sf-toolbar-value"><?php echo $collector->getMagentoVersion() ?></span>

    </div>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group">

            <div class="sf-toolbar-info-piece">
                <b>Website</b>
                <span><?php echo $collector->getWebsiteName() ?> (<?php echo $collector->getWebsiteCode() ?>) </span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b>Store</b>
                <span><?php echo $collector->getStoreName() ?> (<?php echo $collector->getStoreCode() ?>) </span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b>Profiler token</b>
                <span>
                    <?php $profilerUrl =  Mage::helper('ecocode_profiler')->getUrl($collector->getToken()) ?>
                    <a href="<?php echo $profilerUrl?>"><?php echo $collector->getToken()?></a>
                </span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b>Admin Url</b>
                <span>
                    <?php $adminUrl = Mage::helper('adminhtml')->getUrl('adminhtml'); ?>
                    <a href="<?php echo $adminUrl?>">Admin</a>
                </span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b>Developermode</b>
                <span>
                    <?php echo $collector->isDeveloperMode() ? 'on' : 'off'; ?>
                </span>
            </div>
        </div>

        <div class="sf-toolbar-info-group">
            <div class="sf-toolbar-info-piece sf-toolbar-info-php">
                <b>PHP version</b>
                <span>
                    <?php echo $collector->getPhpVersion() ?>
                    <a href="<?php echo Mage::getUrl('_profiler/index/phpinfo') ?> ">View phpinfo()</a>
                </span>
            </div>

            <div class="sf-toolbar-info-piece sf-toolbar-info-php-ext">
                <b>PHP Extensions</b>
                <span
                    class="sf-toolbar-status sf-toolbar-status-<?php echo $collector->hasXDebug() ? 'green' : 'red' ?>">xdebug</span>
                <span
                    class="sf-toolbar-status sf-toolbar-status-<?php echo $collector->hasAccelerator() ? 'green' : 'red' ?>">accel</span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b>PHP SAPI</b>
                <span><?php echo $collector->getSapiName() ?></span>
            </div>
        </div>
    </div>
</div>