<?php $prefix = $this->getData('prefix');?>
<table class="alt queries-table">
    <thead>
    <tr>
        <th class="nowrap">#</th>
        <th class="nowrap">Time<span></span></th>
        <th style="width: 100%;">Info</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getData('queries') as $index => $queryData): ?>
        <tr>
            <td class="nowrap"><?php echo $index + 1 ?> </td>
            <td class="nowrap"><?php echo sprintf('%0.2f', $queryData['time'] * 1000)?> ms</td>
            <td>
                <?php echo $this->formatQuery($queryData['sql'], true) ?>
                <div>
                    <strong class="font-normal text-small">Parameters</strong>:
                    <?php echo $this->dumpParameters($queryData['params']) ?>

                </div>
                <div>
                    <strong class="font-normal text-small">Context</strong>:
                    <?php echo $queryData['context'] ?>
                </div>

                <div class="text-small font-normal">
                    <?php if (isset($queryData['trace'])):?>
                        <a href="#" class="sf-toggle link-inverse" data-toggle-selector="#stack-<?php echo $prefix . $index?>" data-toggle-alt-content="Hide stack trace">Show trace</a>
                    <?php endif;?>
                    <a href="#" class="sf-toggle link-inverse" data-toggle-selector="#formatted-query-<?php echo $prefix . $index?>" data-toggle-alt-content="Hide formatted query">View formatted query</a>
                    <a href="#" class="sf-toggle link-inverse" data-toggle-selector="#original-query-<?php echo $prefix . $index?>" data-toggle-alt-content="Hide runnable query">View runnable query</a>
                </div>

                <div id="formatted-query-<?php echo $prefix . $index?>" class="sql-runnable hidden">
                    <?php echo $this->formatQuery($queryData['sql']); ?>
                </div>

                <div id="original-query-<?php echo $prefix . $index?>" class="sql-runnable hidden">
                    <?php echo $this->formatQuery($this->replaceQueryParameters($queryData['sql'], $queryData['params']), true); ?>
                </div>

                <?php if (isset($queryData['trace'])):?>
                    <div id="stack-<?php echo $prefix . $index ?>" class="hidden">
                        <strong class="font-normal text-small">Trace</strong>:
                        <ul class="sf-call-stack ">

                            <?php foreach($queryData['trace'] as $item): ?>
                                <li>
                                    <?php echo isset($item['class']) ? $item['class'] . '::'  : ''?><?php echo $item['function']?><br>
                                    <small><?php echo $item['file']?>::<?php echo $item['line']?></small>
                                </li>

                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif;?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>