<?php
/** @var Ecocode_Profiler_Model_Profile $profile */
$profile = Mage::registry('current_profile');

$request = $this->getRequest();
$token = false;
if ($profile && $profile->getToken()) {
    $token = $profile->getToken();
}
?>

<div id="sidebar">
    <div id="sidebar-shortcuts">
        <div class="shortcuts">
            <a href="#" class="visible-small"
               onclick="Sfjs.toggleClass(document.getElementById('sidebar'), 'expanded'); return false;">
                <span class="icon">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewBox="0 0 24 24" xml:space="preserve">
                    <path fill="#AAAAAA" d="m 2.571,17.5 18.859,0 c 0.87,0 1.57,0.7 1.57,1.57 l 0,1.57 c 0,0.87 -0.7,1.57 -1.57,1.57 l -18.859,0 C 1.702,22.21 1,21.51 1,20.64 L 1,19.07 C 1,18.2 1.702,17.5 2.571,17.5 Z M 1,11.21 1,12.79 c 0,0.86 0.702,1.56 1.571,1.56 l 18.859,0 c 0.87,0 1.57,-0.7 1.57,-1.56 l 0,-1.58 C 23,10.35 22.3,9.644 21.43,9.644 l -18.859,0 C 1.702,9.644 1,10.35 1,11.21 Z M 1,3.357 1,4.929 c 0,0.869 0.702,1.572 1.571,1.572 l 18.859,0 C 22.3,6.501 23,5.798 23,4.929 L 23,3.357 C 23,2.489 22.3,1.786 21.43,1.786 l -18.859,0 C 1.702,1.786 1,2.489 1,3.357 Z" />
                    </svg>
                </span>
            </a>

            <a class="btn btn-sm" href="<?php echo Mage::getUrl('_profiler/index/search', ['limit' => 10])?>">Last 10</a>
            <a class="btn btn-sm"
               href="<?php echo Mage::helper('ecocode_profiler')->getUrl('latest'); ?>">Latest</a>

            <a class="sf-toggle btn btn-sm" data-toggle-selector="#sidebar-search" <?php echo $token ?: 'data-toggle-initial="display"'?>>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24"
                     viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
                    <path fill="#AAAAAA" d="M11.61,0.357c-4.4,0-7.98,3.58-7.98,7.98c0,1.696,0.526,3.308,1.524,4.679l-4.374,4.477
                        c-0.238,0.238-0.369,0.554-0.369,0.891c0,0.336,0.131,0.653,0.369,0.891c0.238,0.238,0.554,0.369,0.891,0.369
                        c0.336,0,0.653-0.131,0.893-0.371l4.372-4.475c1.369,0.996,2.98,1.521,4.674,1.521c4.4,0,7.98-3.58,7.98-7.98
                        S16.01,0.357,11.61,0.357z M17.07,8.337c0,3.011-2.449,5.46-5.46,5.46c-3.011,0-5.46-2.449-5.46-5.46s2.449-5.46,5.46-5.46
                        C14.62,2.877,17.07,5.326,17.07,8.337z"/>
                </svg>
                <span class="hidden-small">Search</span>
            </a>

            <!--{{ render(path('_profiler_search_bar', request.query.all)) }}-->
            <div id="sidebar-search">
                <form action="<?php echo Mage::getUrl('_profiler/index/search', [])?>" method="get">
                    <div class="form-group">
                        <label for="ip">IP</label>
                        <input type="text" name="ip" id="ip" value="<?php echo $request->getParam('ip');?> ">
                    </div>

                    <div class="form-group">
                        <label for="method">Method</label>
                        <select name="method" id="method">
                            <option value="">Any</option>
                            <?php foreach (['DELETE', 'GET', 'HEAD', 'PATCH', 'POST', 'PUT'] as $m):?>
                                <option <?php echo $request->getParam('method') === $m ? 'selected="selected"' : ''?>><?php echo $m?></option>
                            <?php endforeach;?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="status_code">Status</label>
                        <input type="number" name="status_code" id="status_code" value="<?php echo $request->getParam('status_code');?>">
                    </div>

                    <div class="form-group">
                        <label for="url">URL</label>
                        <input type="text" name="url" id="url" value="<?php echo $request->getParam('url');?>">
                    </div>

                    <div class="form-group">
                        <label for="token">Token</label>
                        <input type="text" name="_token" id="token" value="<?php echo $request->getParam('_token');?>">
                    </div>

                    <div class="form-group">
                        <label for="start">From</label>
                        <input type="date" name="start" id="start" value="<?php echo $request->getParam('start');?>">
                    </div>

                    <div class="form-group">
                        <label for="end">Until</label>
                        <input type="date" name="end" id="end" value="<?php echo $request->getParam('end');?>">
                    </div>

                    <div class="form-group">
                        <label for="limit">Results</label>
                        <select name="limit" id="limit">
                            <?php foreach ([10, 50, 100]  as $l):?>
                                <option <?php echo $request->getParam('limit') === $l ? 'selected="selected"' : ''?>><?php echo $l?></option>
                            <?php endforeach;?>
                        </select>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-sm">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <ul id="menu-profiler">
        <?php echo $this->getChildHtml('menu'); ?>
    </ul>
</div>