<?php
/** @var Ecocode_Profiler_Model_Collector_CacheDataCollector $collector */
$collector = $this->getCollector();
$token     = $this->getToken();

$cacheList  = $collector->getCacheList();
$cacheTypes = Mage::app()->getCacheInstance()->getTypes();
?>

<div
    class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getName() ?>">
    <a target="_blank"
       href="<?php echo Mage::helper('ecocode_profiler')->getCollectorUrl($token, $collector); ?>">
        <div class="sf-toolbar-icon">
            <svg width="24" height="24" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                <path fill="#AAAAAA" d="M1168 1216q0 33-23.5 56.5t-56.5 23.5-56.5-23.5-23.5-56.5 23.5-56.5 56.5-23.5 56.5 23.5 23.5 56.5zm256 0q0 33-23.5 56.5t-56.5 23.5-56.5-23.5-23.5-56.5 23.5-56.5 56.5-23.5 56.5 23.5 23.5 56.5zm112 160v-320q0-13-9.5-22.5t-22.5-9.5h-1216q-13 0-22.5 9.5t-9.5 22.5v320q0 13 9.5 22.5t22.5 9.5h1216q13 0 22.5-9.5t9.5-22.5zm-1230-480h1180l-157-482q-4-13-16-21.5t-26-8.5h-782q-14 0-26 8.5t-16 21.5zm1358 160v320q0 66-47 113t-113 47h-1216q-66 0-113-47t-47-113v-320q0-25 16-75l197-606q17-53 63-86t101-33h782q55 0 101 33t63 86l197 606q16 50 16 75z"/>
            </svg>
            <span class="sf-toolbar-value"><?php echo sprintf('%0.2f', $collector->getTotalTime() * 1000) ?> ms</span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group" style="float: left;">
            <?php foreach ($cacheList as $cache): ?>
                <?php $currentStatus = $cacheTypes[$cache['id']]->getData('status'); ?>
                <div class="sf-toolbar-info-piece">
                    <b><?php echo uc_words($cache['id'], ' ')?></b>
                    <?php if($cache['status'] == 1): ?>
                        <span class="sf-toolbar-status sf-toolbar-status-green">Yes</span>
                    <?php else:?>
                        <span class="sf-toolbar-status">No</span>
                    <?php endif;?>
                    &nbsp;
                    <?php if ($currentStatus): ?>
                        <a href="#"
                           data-url="<?php echo Mage::getUrl('_profiler/cache/clear', ['types' => $cache['id']]) ?>"
                           class="btn btn-sm ajax-action">Clear</a> /
                        <a href="#"
                           data-url="<?php echo Mage::getUrl('_profiler/cache/disable', ['types' => $cache['id']]) ?>"
                           class="btn btn-sm ajax-action">Disable</a>
                    <?php else: ?>
                        <a href="#"
                           data-url="<?php echo Mage::getUrl('_profiler/cache/enable', ['types' => $cache['id']]) ?>"
                           class="btn btn-sm ajax-action">Enable</a>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="sf-toolbar-info-group" >
            <div class="sf-toolbar-info-piece">
                <b>Cache calls</b>
                <span class="sf-toolbar-status"><?php echo $collector->getStats('total') ?></span>
            </div>

            <div class="sf-toolbar-info-piece">
                <b>Time</b>
                <span><?php echo sprintf('%0.2f', $collector->getTotalTime() * 1000) ?> ms</span>
            </div>
        </div>

    </div>

</div>