<?php
/** @var Ecocode_Profiler_Model_Collector_CacheDataCollector $collector */
$collector = $this->getCollector();
$token     = $this->getToken();

$cacheList = $collector->getCacheList();
?>

<div
    class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getName() ?>">
    <a target="_blank"
       href="<?php echo Mage::getUrl('_profiler/index/panel', ['token' => $token, 'panel' => $collector->getName()]) ?>">
        <div class="sf-toolbar-icon">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
                <path fill="#AAAAAA" d="M15.1,4.3c-2.1-0.5-4.2-0.5-6.2,0C8.6,4.3,8.2,4.1,8.2,3.8V3.4c0-1.2,1-2.3,2.3-2.3h3c1.2,0,2.3,1,2.3,2.3
                    v0.3C15.8,4.1,15.4,4.3,15.1,4.3z M20.9,14c0,4.9-4,8.9-8.9,8.9s-8.9-4-8.9-8.9s4-8.9,8.9-8.9S20.9,9.1,20.9,14z M16.7,15
                    c0-0.6-0.4-1-1-1H13V8.4c0-0.6-0.4-1-1-1s-1,0.4-1,1v6.2c0,0.6,0.4,1.3,1,1.3h3.7C16.2,16,16.7,15.6,16.7,15z"></path>
            </svg>
            <span class="sf-toolbar-value"></span>
        </div>
    </a>
    <div class="sf-toolbar-info" style="left: 0px;">
        <?php foreach ($cacheList as $cache): ?>
            <div class="sf-toolbar-info-piece">
                <b><?php echo uc_words($cache['id'], ' ')?></b>
                <?php if($cache['status'] == 1): ?>
                    <span class="sf-toolbar-status sf-toolbar-status-green">Yes</span>
                <?php else:?>
                    <span class="sf-toolbar-status">No</span>
                <?php endif;?>
            </div>
        <?php endforeach; ?>
    </div>

</div>