<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="robots" content="noindex,nofollow"/>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <title>Magento Profiler</title>
    <link rel="icon" type="image/x-icon" sizes="16x16"
          href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBI
WXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH4AkNDCcsxO0sbAAAAYBJREFUOMvdk80rZXEYxz/PPV6u
bDBervHSdWaklLJQVrKxslQ2QoqNjS5ZTDTNyPYmFrIh6pDF/QvUNOU/UEgmLoW8zGAl3Ov8ntmc
ezt0yGznu/ye7/OpU5+f8Equeux6YzEDhEFGI87hTtBOXha3A9GilAl9USUG5Ht1GnTZPOVOflz/
9ScQoN1YVwWfhlR1GigDnkAXvNkwkAP8FpGv5feHi5LAzQLO+6LtoqFZhGaP9xNDLLKW3AY4661r
sERmgE4PuCe4oxXO8YYAXPTZ10AJcKDoRKVzlAj638t+u0OVOaARuIk4yQ85/kE6L9Vas3R6czsQ
LXp0Q98qHpLjAJdhO55vmanileSPk8HqttxU3nXmJuQHhLUwDfBorF0g5vsU87rsJhCQjWrJu7pX
Af+Q/wWgmC6UrfefyZ5gevD0pNI53tRuWviMPhMnbMdfnpbW7t+xS1NG5axIksDF80+ReUFHfC6k
FZkHkO+YN19jJj7/cVXHqlaP9oN2fwF3BYdp8BgRAQAAAABJRU5ErkJggg==">
    <?php echo $this->getChildHtml('profiler_head'); ?>
    <style type="text/css">
        <?php echo $this->getChildHtml('profiler_css'); ?>
    </style>
    <script>
        <?php echo $this->getChildHtml('profiler_js'); ?>
    </script>
</head>
<body>
<div id="header">
    <div class="container">
        <h1>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="svgMageLogo"
                 width="24" xml:space="preserve" height="24" viewBox="0 0 53.692 62" baseProfile="" version="1.1"
                 y="0px" x="0px">
                <g fill="#E85D22">
                    <path d="m26.845 8.857"/>
                    <polygon points="53.692 15.5 53.692 46.5 46.021 50.929 46.021 19.929 26.845 8.857 7.67 19.928 7.67 50.929 0 46.5 0 15.5 26.845 0"/>
                    <polygon points="26.847 62 15.341 55.356 15.341 24.357 23.011 19.928 23.011 50.929 26.845 53.257 30.682 50.929 30.682 19.929 38.353 24.357 38.353 55.356"/>
                </g>
            </svg>
            Magento <span>Profiler</span>
        </h1>
    </div>
    <div class="logo-ecocode" style="float: right">
        <a href="http://www.ecocode.de">
            <img height="28px" src="https://www.ecocode.de/wp-content/uploads/2014/03/logo1.png"><br>
            <small>Made with Herzblut in Berlin</small>
        </a>
    </div>
</div>


<div id="summary">
    <?php echo $this->getChildHtml('summery'); ?>
</div>

<div id="content" class="container">
    <div id="main">
        <div id="collector-wrapper">
            <div id="collector-content">
                <?php echo $this->getChildHtml('content'); ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('left'); ?>
    </div>
</div>


</body>
</html>
