<?php
/** @var Ecocode_Profiler_Model_Collector_CustomerDataCollector $collector */
$collector = $this->getCollector();
$token     = $this->getToken();
?>


<div
    class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getName() ?>">
    <div class="sf-toolbar-icon">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
            <path fill="#AAAAAA" d="M21,20.4V22H3v-1.6c0-3.7,2.4-6.9,5.8-8c-1.7-1.1-2.9-3-2.9-5.2c0-3.4,2.7-6.1,6.1-6.1s6.1,2.7,6.1,6.1c0,2.2-1.2,4.1-2.9,5.2C18.6,13.5,21,16.7,21,20.4z"/>
        </svg>
        <span class="sf-toolbar-value">
            <?php if ($collector->isLoggedIn()): ?>
                <?php echo $collector->getCustomerEmail(); ?>
            <?php else: ?>
                n/a
            <?php endif; ?>
        </span>

    </div>
    <div class="sf-toolbar-info">
        <?php if ($collector->isLoggedIn()): ?>
            <div class="sf-toolbar-info-piece">
                <b>Logged in as</b>
                <span><?php echo $collector->getCustomerEmail(); ?></span>
            </div>
            <div class="sf-toolbar-info-piece">
                <b>Name</b>
                <span><?php echo $collector->getCustomerName(); ?></span>
            </div>
        <?php endif; ?>

        <div class="sf-toolbar-info-piece">
            <b>Customer Group</b>
            <span><?php echo $collector->getGroupCode(); ?> (Id: <?php echo $collector->getGroupId(); ?>) </span>
        </div>

        <div class="sf-toolbar-info-piece">
            <b>Tax Class</b>
            <span><?php echo $collector->getTaxClassName(); ?> (Id: <?php echo $collector->getTaxClassId(); ?>) </span>
        </div>
    </div>
</div>