<?php
/** @var Ecocode_Profiler_Model_Collector_LayoutDataCollector $collector */
$collector = $this->getCollector();
$token     = $this->getToken();
?>

<div
    class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getName() ?>">
    <a target="_blank"
       href="<?php echo Mage::helper('ecocode_profiler')->getCollectorUrl($token, $collector); ?>">
        <div class="sf-toolbar-icon">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
        <path fill="#AAAAAA" d="M20.1,1H3.9C2.3,1,1,2.3,1,3.9v16.3C1,21.7,2.3,23,3.9,23h16.3c1.6,0,2.9-1.3,2.9-2.9V3.9
            C23,2.3,21.7,1,20.1,1z M21,20.1c0,0.5-0.4,0.9-0.9,0.9H3.9C3.4,21,3,20.6,3,20.1V3.9C3,3.4,3.4,3,3.9,3h16.3C20.6,3,21,3.4,21,3.9
            V20.1z M5,5h14v3H5V5z M5,10h3v9H5V10z M10,10h9v9h-9V10z"/>
        </svg>
            <span class="sf-toolbar-value"><?php echo sprintf('%0.0f', $collector->getTotalRenderTime() * 1000)?> <span class="unit">ms</span></span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group" >
            <div class="sf-toolbar-info-piece">
                <b>Layout handles</b>
                <?php foreach ($collector->getLayoutHandles() as $handle): ?>
                    <?php echo $handle ?><br>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="sf-toolbar-info-group" >
            <div class="sf-toolbar-info-piece">
                <b>Render Time</b>
                <span><?php echo sprintf('%0.0f', $collector->getTotalRenderTime() * 1000)?> ms</span>
            </div>


            <div class="sf-toolbar-info-piece">
                <b>Block created</b>
                <span class="sf-toolbar-status"><?php echo $collector->getBlocksCreatedCount()?></span>
            </div>


            <div class="sf-toolbar-info-piece">
                <b>Block rendered</b>
                <span class="sf-toolbar-status"><?php echo $collector->getBlocksRenderedCount()?></span>
            </div>
        </div>
    </div>
</div>