<?php
/** @var Ecocode_Profiler_Model_Profile $profile */
$profile = Mage::registry('current_profile');

/** @var Ecocode_Profiler_Helper_Data $helper */
$helper = Mage::helper('ecocode_profiler');

/** @var Ecocode_Profiler_Helper_Code $codeHelper */
$codeHelper = Mage::helper('ecocode_profiler/code');
?>
<?php if ($profile): ?>
    <?php
    /** @var Ecocode_Profiler_Model_Collector_RequestDataCollector $requestCollector */
    $requestCollector = $profile->getCollector('request');
    $statusCode       = $requestCollector->getStatusCode();
    $cssClass         = ($statusCode > 399) ? 'status-error' : $statusCode > 299 ? 'status-warning' : 'status-success';
    ?>

    <div class="status <?php echo $cssClass ?>">
        <div class="container">
            <h2 class="break-long-words">
                <?php if (in_array(strtoupper($profile->getMethod()), ['GET', 'HEAD'])): ?>
                    <a href="<?php echo $profile->getUrl() ?>"><?php echo $profile->getUrl() ?></a>
                <?php else: ?>
                    <?php echo $profile->getUrl() ?>
                <?php endif; ?>
            </h2>

            <?php if ($redirect = $requestCollector->getRedirect()): ?>
                <?php
                $controller    = $redirect['controller'];
                $redirectRoute = '@' . $redirect['route'];
                ?>
                <dl class="metadata">
                    <dt>
                        <span class="label"><?php echo $redirect['status_code'] ?></span>
                        Redirect from
                    </dt>
                    <dd>
                        <?php echo $redirect['method'] == 'GET' ? '' : $redirect['method'] ?>
                        <?php if ($controller = $redirect['controller']): ?>
                            <?php $link = $codeHelper->getFileLink($controller['file'], $controller['line']); ?>

                            <?php if ($link): ?>
                                <a target="profiler_link_target" href="<?php echo $link ?>"
                                   title="<?php echo $controller['file'] ?>">
                                    <?php echo $redirectRoute; ?>
                                </a>
                            <?php else: ?>
                                <?php echo $redirectRoute; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        (<a href="<?php echo $helper->getUrl($redirect['token']) ?>"><?php echo $redirect['token']; ?></a>)
                    </dd>
                </dl>
            <?php endif; ?>

            <!--        {% if request_collector and request_collector.forward|default(false) and request_collector.forward.controller.class is defined -%}
                    {%- set forward = request_collector.forward -%}
                    {%- set controller = forward.controller -%}
                    <dl class="metadata">
                        <dt>Forwarded to</dt>
                        <dd>
                            {% set link = controller.file|file_link(controller.line) -%}
                            {%- if link %}<a href="{{ link }}" title="{{ controller.file }}">{% endif -%}
                                {{- controller.class|abbr_class|striptags -}}
                                {{- controller.method ? ' :: ' ~ controller.method }}
                                {%- if link %}</a>{% endif %}
                            (<a href="{{ path('_profiler', { token: forward.token }) }}">{{ forward.token }}</a>)
                        </dd>
                    </dl>
                    {%- endif %}-->

            <dl class="metadata">
                <dt>Method</dt>
                <dd><?php echo strtoupper($profile->getMethod()) ?></dd>

                <?php if ($profile->hasCollector('request')): ?>
                    <?php
                    /** @var Ecocode_Profiler_Model_Collector_RequestDataCollector $collector */
                    $collector = $profile->getCollector('request');
                    ?>
                    <dt>Route</dt>
                    <dd>
                        <?php if ($controller = $collector->getController()): ?>
                            <?php $link = $codeHelper->getFileLink($controller['file'], $controller['line']); ?>

                            <?php if ($link): ?>
                                <a target="profiler_link_target" href="<?php echo $link ?>"
                                   title="<?php echo $controller['file'] ?>">
                                    @<?php echo $collector->getRoute(); ?>
                                </a>
                            <?php else: ?>
                                @<?php echo $collector->getRoute(); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </dd>
                <?php endif; ?>

                <dt>HTTP Status</dt>
                <dd><?php echo $statusCode ?></dd>

                <dt>IP</dt>
                <dd><?php echo $profile->getIp() ?></dd>

                <dt>Profiled on</dt>
                <dd><?php echo date('r', $profile->getTime()) ?></dd>

                <dt>Token</dt>
                <dd><?php echo $profile->getToken(); ?></dd>
            </dl>
        </div>
    </div>
<?php endif; ?>
